### ISSUE TITLE
Version 0.2.1 is detected by curse as a forge mod, when it's not.

### ISSUE THREAD

**Issue by Darkmega18** [mim1q/ConvenientNameTags#14]
Yeah. I think you forgot to tag it properly. it appeared in my launcher and I really wanted to download it, but I realized quickly all the other versions were fabric. :V

Well, while I'm at it, I might aswell ask:
Is there any chance for an official port of these features to forge by any chance? Serilum has a nametag mod but it's not as feature complete as yours.

**Comment by mim1q** [comment]
Oh, yeah. Must've forgot to tag it. Fixed - it's now properly tagged as Fabric!
As for the port - nope, I'm a Fabric-only dev. Sorry 😅 And thank you for reporting!
